### ISSUE TITLE
PRACTICA3

### ISSUE THREAD

**Issue by Nelsy21** [SistemasTecTlaxiaco/actividad-3-practica-architect-Nelsy21#1]
[PRACTICA3_INGENIERIA_DE_SOFTWARE.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-architect-Nelsy21/files/12554073/PRACTICA3_INGENIERIA_DE_SOFTWARE.pdf)

**Comment by Eve-lizet** [comment]
Calificacion 18/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
